### ISSUE TITLE
Broken link to source repo

### ISSUE THREAD

**Issue by peacepenguin** [GluuFederation/docs-supergluu-prod#3]
There is a dead link for the source code repo of oxPush3. The repo seems to be gone. Is there a new location for oxPush3 / Super Gluu?

Here's the details:
Note Super Gluu is based on the free open source **oxPush3 project**.
  
dead link on "oxPush3 project"
https://github.com/GluuFederation/oxPush3

The dead link shows up on this public document page:
https://gluu.org/docs/supergluu/3.1.3/developer-guide/

Appears that the content is sourced from:
https://github.com/GluuFederation/docs-supergluu-prod/blob/3.1.3/3.1.3/sources/developer-guide/index.md

**Comment by willow9886** [comment]
Thanks. Removed. 

https://github.com/GluuFederation/docs-supergluu-prod/commit/7287260b70d1e51f5176997efed333e1fa677e67

That repo has been deprecated.
